### ISSUE TITLE
Multiple bugs in Human class.

### ISSUE THREAD

**Issue by bynux-gh** [YHWH-333/earth#1]
The machine learning algorithm for Humans seems _immensely_ flawed. There are a couple issues I've come across:

- Human nature incentivizes narcissists (those with low `moralAlignment`/selflessness) to take on leadership roles; it also encourages others to place such people in these roles.
- AI prioritizes competition over cooperation. Humans will work disproportionately harder to increase their own status than to assist others in doing the same.
- Auto-generated souls are occasionally self-destructive. They may lead humans to take on self-defeating habits, or to desire (and in some cases cause) their own destruction. This is often to the dismay of other Humans.

Most of these traits are either uncommon or contextually harmless in other animals. Suggesting a rework of the Soul AI algorithm that better encompasses their more advanced "intelligence."

**Comment by YHWH-333** [comment]
The aforementioned "issues" are all either inherent to the Human algorithm (as you said) or are a desired part of simulation. It is not possible at this time to update the code in a running simulation; if I were to update the Soul right now, it would wipe the current simulation entirely. I'm sure you would rather carry on and let the sim run its course than have a literal _universe_ wiped from existence.

**Comment by bynux-gh** [comment]
Noted. Consider tweaking on next simulation.
