### ISSUE TITLE
Overfitting issues with the AI?

### ISSUE THREAD

**Issue by Papayaman1000** [YHWH-333/earth#4]
The "Creativity" skill is supposed to let humans generate totally new assets that are added to the game, but a lot of the time you get a bunch of different ones that all come up with stuff that's super similar or exactly the same out of nowhere. This usually causes a huge fight within the playerbase. Since the AI behind the creation process is trained off of past products, do you think they could be related?

Also, as an aside, that process gives a `null` output with concerning frequency.

**Comment by YHWH-333** [comment]
This, like the problems with human tendencies toward dumb decisions (Issue #1), is entirely a problem with the AI. Instances with similar backgrounds will produce similar results when presented with an opportunity for creativity. Also like with Issue 1, a reupload of the Soul AI would require a restart of the whole simulation.

For the time being I encourage instances with awareness of this, such as yourself, to point out that this just happens sometimes. Nothing wrong with having the same idea as someone else; isn't that how you guys discovered calculus? ;)
