### ISSUE TITLE
i beat someone in pvp

### ISSUE THREAD

**Issue by heavenly** [YHWH-333/earth#9]
now they are dragging me off to a temporary holding dungeon, is this a bug or was I not in a pvp enabled zone

**Comment by YHWH-333** [comment]
~~What do you mean _PVP_ ?! Do you think this is some sort of game? I specifically commanded your kind _not_ to delete other `Human` instances. I'm glad to see they've developed an in-simulation system to punish those who do.~~ 

I'm sorry for the Linus Torvalds-style rant. No, this is not a bug.
